CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
    uid VARCHAR(255) NOT NULL,
    tele_id BIGINT NOT NULL,
    tele_name VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT now(),
	 currency VARCHAR(255),
	 lang VARCHAR(255),
    is_terms BOOLEAN NOT NULL DEFAULT 'f'
);

CREATE TABLE IF NOT EXISTS users_base(
    id SERIAL PRIMARY KEY NOT NULL,
    tele_id BIGINT NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    conclusion BIGINT NOT NULL DEFAULT 0,
	 is_premium BOOLEAN NOT NULL DEFAULT 'f',
    verification BOOLEAN NOT NULL DEFAULT 'f'
);

CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS collections (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	count INTEGER NOT NULL DEFAULT 0,
	collection_uid VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	price NUMERIC(10,2) DEFAULT 0,
	author VARCHAR(255) NOT NULL,
	blockchain VARCHAR(255) NOT NULL,
	uid_collection VARCHAR(255) NOT NULL,
	token_uid VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS admins(
    id SERIAL PRIMARY KEY NOT NULL,
    tele_id BIGINT NOT NULL,
	 count_referrals BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS referral(
	id SERIAL PRIMARY KEY NOT NULL,
	tele_id BIGINT NOT NULL,
	tele_name VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT now(),
	admin_referral BIGINT NOT NULL
);